repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: latest
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=1024"] # 1 MB
  - repo: https://github.com/psf/black
    rev: latest
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: latest
    hooks:
      - id: isort
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: latest
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/python/mypy
    rev: latest
    hooks:
      - id: mypy
