# General settings
pipeline:
  - normalize_input
  - preprocess_image
  # - layout_analysis
  # - enhance_image
  # - ocr
  # - post_ocr_cleanup
  # - final_output

# Step-specific configurations
steps:
  normalize_input:
    dpi: 300
    output_format: "png"

  preprocess_image:
    grayscale: true
    denoise:
      enabled: true
      kernel_size: [5, 5]
    threshold:
      enabled: true
      method: "adaptive_gaussian" # or "otsu", "simple"
      block_size: 11
      c_value: 2
    deskew:
      enabled: true

  enhance_image:
    dewarp:
      enabled: false # requires DocUNet model
    super_resolution:
      enabled: false # requires ESRGAN model

  layout_analysis:
    provider: "layoutparser" # or "tesseract"

  ocr:
    provider: "tesseract"
    tesseract:
      oem: 1 # LSTM engine
      psm: 6 # single uniform block of text
      lang: "eng"

  post_ocr_cleanup:
    spell_correction:
      enabled: true
      provider: "symspell" # requires dictionary

# I/O directories
paths:
  input: "input"
  output: "output"
  models: "models"

# Parallel processing settings
dask:
  enabled: true
  # Number of workers, can be set to -1 to use all available cores
  n_workers: -1
